// <auto-generated />
using System;
using CAAMSAirlineWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CAAMSAirlineWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260318035729_InitialFinalSchema")]
    partial class InitialFinalSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Aircraft", b =>
                {
                    b.Property<int>("AircraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Aircraft_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AircraftId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AircraftId");

                    b.ToTable("Aircrafts", (string)null);
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Airport", b =>
                {
                    b.Property<string>("AirportCode")
                        .HasColumnType("char(3)")
                        .HasColumnName("Airport_code");

                    b.Property<string>("AirportName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Airport_name");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AirportCode");

                    b.ToTable("Airports", (string)null);
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.AppUser", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("First_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Username");

                    b.ToTable("AppUsers", (string)null);
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Baggage", b =>
                {
                    b.Property<int>("BaggageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Baggage_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BaggageId"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("Ticket_id");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("BaggageId");

                    b.HasIndex("TicketId");

                    b.ToTable("Baggages", (string)null);
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Booking_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Booking_date");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("Customer_id");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Total_price");

                    b.HasKey("BookingId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Customer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<DateTime>("DOB")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("First_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Last_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Flight_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightId"));

                    b.Property<int>("AircraftId")
                        .HasColumnType("int")
                        .HasColumnName("Aircraft_id");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Base_price");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Flight_number");

                    b.HasKey("FlightId");

                    b.HasIndex("AircraftId");

                    b.ToTable("Flights", (string)null);
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.FlightLeg", b =>
                {
                    b.Property<int>("LegId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Leg_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LegId"));

                    b.Property<string>("ArrivalAirport")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("Arrival_airport");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Arrival_time");

                    b.Property<string>("DepartureAirport")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("Departure_airport");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Departure_time");

                    b.Property<int>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("Flight_id");

                    b.Property<int>("LegNumber")
                        .HasColumnType("int")
                        .HasColumnName("Leg_number");

                    b.HasKey("LegId");

                    b.HasIndex("ArrivalAirport");

                    b.HasIndex("DepartureAirport");

                    b.HasIndex("FlightId", "LegNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_FlightLeg");

                    b.ToTable("FlightLegs", (string)null);
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.FlightStaff", b =>
                {
                    b.Property<int>("FlightStaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Flight_staff_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightStaffId"));

                    b.Property<int>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("Flight_id");

                    b.Property<int>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("Staff_id");

                    b.HasKey("FlightStaffId");

                    b.HasIndex("FlightId");

                    b.HasIndex("StaffId");

                    b.ToTable("FlightStaffs", (string)null);
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.FlightStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Status_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<int>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("Flight_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Updated_at");

                    b.HasKey("StatusId");

                    b.HasIndex("FlightId");

                    b.ToTable("FlightStatuses", (string)null);
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Passenger", b =>
                {
                    b.Property<int>("PassengerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PassengerId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PassengerId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("First_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Last_name");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Passport_number");

                    b.HasKey("PassengerId");

                    b.HasIndex("BookingId");

                    b.ToTable("Passenger", (string)null);
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("Booking_id");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Payment_date");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Payment_method");

                    b.HasKey("PaymentId");

                    b.HasIndex("BookingId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Seat_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatId"));

                    b.Property<int>("AircraftId")
                        .HasColumnType("int")
                        .HasColumnName("Aircraft_id");

                    b.Property<string>("SeatClass")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Seat_class");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Seat_number");

                    b.HasKey("SeatId");

                    b.HasIndex("AircraftId", "SeatNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_Seat");

                    b.ToTable("Seats", (string)null);
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Staff_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("First_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Last_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StaffId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Staffs", (string)null);
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Ticket_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("Booking_id");

                    b.Property<int>("LegId")
                        .HasColumnType("int")
                        .HasColumnName("Leg_id");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int")
                        .HasColumnName("Passenger_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("SeatId")
                        .HasColumnType("int")
                        .HasColumnName("Seat_id");

                    b.Property<string>("TicketClass")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Ticket_class");

                    b.HasKey("TicketId");

                    b.HasIndex("LegId");

                    b.HasIndex("PassengerId");

                    b.HasIndex("SeatId");

                    b.HasIndex("BookingId", "PassengerId", "LegId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Ticket");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Baggage", b =>
                {
                    b.HasOne("CAAMSAirlineWebApp.Models.Ticket", "Ticket")
                        .WithMany("Baggages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Baggage_Ticket");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Booking", b =>
                {
                    b.HasOne("CAAMSAirlineWebApp.Models.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Booking_Customer");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Customer", b =>
                {
                    b.HasOne("CAAMSAirlineWebApp.Models.AppUser", "AppUser")
                        .WithOne("Customer")
                        .HasForeignKey("CAAMSAirlineWebApp.Models.Customer", "Username")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Customers_AppUsers");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Flight", b =>
                {
                    b.HasOne("CAAMSAirlineWebApp.Models.Aircraft", "Aircraft")
                        .WithMany("Flights")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Flight_Aircraft");

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.FlightLeg", b =>
                {
                    b.HasOne("CAAMSAirlineWebApp.Models.Airport", "ArrivalAirportNavigation")
                        .WithMany("ArrivalFlightLegs")
                        .HasForeignKey("ArrivalAirport")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FlightLeg_ArrivalAirport");

                    b.HasOne("CAAMSAirlineWebApp.Models.Airport", "DepartureAirportNavigation")
                        .WithMany("DepartureFlightLegs")
                        .HasForeignKey("DepartureAirport")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FlightLeg_DepartureAirport");

                    b.HasOne("CAAMSAirlineWebApp.Models.Flight", "Flight")
                        .WithMany("FlightLegs")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FlightLeg_Flight");

                    b.Navigation("ArrivalAirportNavigation");

                    b.Navigation("DepartureAirportNavigation");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.FlightStaff", b =>
                {
                    b.HasOne("CAAMSAirlineWebApp.Models.Flight", "Flight")
                        .WithMany("FlightStaffs")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FlightStaff_Flight");

                    b.HasOne("CAAMSAirlineWebApp.Models.Staff", "Staff")
                        .WithMany("FlightStaffs")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FlightStaff_Staff");

                    b.Navigation("Flight");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.FlightStatus", b =>
                {
                    b.HasOne("CAAMSAirlineWebApp.Models.Flight", "Flight")
                        .WithMany("FlightStatuses")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FlightStatus_Flight");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Passenger", b =>
                {
                    b.HasOne("CAAMSAirlineWebApp.Models.Booking", "Booking")
                        .WithMany("Passengers")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Passenger_Booking");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Payment", b =>
                {
                    b.HasOne("CAAMSAirlineWebApp.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Payment_Booking");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Seat", b =>
                {
                    b.HasOne("CAAMSAirlineWebApp.Models.Aircraft", "Aircraft")
                        .WithMany("Seats")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Seat_Aircraft");

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Staff", b =>
                {
                    b.HasOne("CAAMSAirlineWebApp.Models.AppUser", "AppUser")
                        .WithOne("Staff")
                        .HasForeignKey("CAAMSAirlineWebApp.Models.Staff", "Username")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Staff_User");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Ticket", b =>
                {
                    b.HasOne("CAAMSAirlineWebApp.Models.Booking", "Booking")
                        .WithMany("Tickets")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_Booking");

                    b.HasOne("CAAMSAirlineWebApp.Models.FlightLeg", "FlightLeg")
                        .WithMany("Tickets")
                        .HasForeignKey("LegId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_FlightLeg");

                    b.HasOne("CAAMSAirlineWebApp.Models.Passenger", "Passenger")
                        .WithMany("Tickets")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_Passenger");

                    b.HasOne("CAAMSAirlineWebApp.Models.Seat", "Seat")
                        .WithMany("Tickets")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Ticket_Seat");

                    b.Navigation("Booking");

                    b.Navigation("FlightLeg");

                    b.Navigation("Passenger");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Aircraft", b =>
                {
                    b.Navigation("Flights");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Airport", b =>
                {
                    b.Navigation("ArrivalFlightLegs");

                    b.Navigation("DepartureFlightLegs");
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.AppUser", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Booking", b =>
                {
                    b.Navigation("Passengers");

                    b.Navigation("Payments");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Customer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Flight", b =>
                {
                    b.Navigation("FlightLegs");

                    b.Navigation("FlightStaffs");

                    b.Navigation("FlightStatuses");
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.FlightLeg", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Passenger", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Seat", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Staff", b =>
                {
                    b.Navigation("FlightStaffs");
                });

            modelBuilder.Entity("CAAMSAirlineWebApp.Models.Ticket", b =>
                {
                    b.Navigation("Baggages");
                });
#pragma warning restore 612, 618
        }
    }
}
